USE EducationDB;
GO

CREATE TABLE Cities(
	CityID INT PRIMARY KEY,
	Name NVARCHAR(150)
);

CREATE TABLE Customers(
	CustomerID INT PRIMARY KEY,
	Name NVARCHAR(150),
	Birthday DATE,
	CityID INT FOREIGN KEY REFERENCES Cities(CityID)
);

CREATE TABLE Orders(
	OrderID INT PRIMARY KEY,
	CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerID)
);

CREATE TABLE ItemTypes(
	ItemTypeID INT PRIMARY KEY,
	Name NVARCHAR(150)
);

CREATE TABLE Items(
	ItemID INT PRIMARY KEY,
	Name NVARCHAR(150),
	ItemTypeID INT FOREIGN KEY REFERENCES ItemTypes(ItemTypeID)
);

CREATE TABLE OrderItems(
	OrderID INT FOREIGN KEY REFERENCES Orders(OrderID),
	ItemID INT FOREIGN KEY REFERENCES Items(ItemID),
	CONSTRAINT Pk_Order_Item PRIMARY KEY (OrderID, ItemID)
);
