CREATE DATABASE University;
GO

USE University;
GO

CREATE TABLE Majors(
	MajorID INT PRIMARY KEY,
	Name NVARCHAR(150)
);

CREATE TABLE Students(
	StudentID INT PRIMARY KEY,
	StudentNumber INT NOT NULL,
	StudentName NVARCHAR(150) NOT NULL,
	MajorID INT FOREIGN KEY REFERENCES Majors(MajorID)
);

CREATE TABLE Subjects(
	SubjectID INT PRIMARY KEY,
	Name NVARCHAR(150)
);

CREATE TABLE Agenda(
	StudentID INT FOREIGN KEY REFERENCES Students(StudentID),
	SubjectID INT FOREIGN KEY REFERENCES Subjects(SubjectID),
	CONSTRAINT Pk_StudentSubject PRIMARY KEY (StudentID, SubjectID)
);

CREATE TABLE Payments(
	PaymentID INT PRIMARY KEY,
	PaymentDate DATE NOT NULL,
	PaymentAmount DECIMAL(10, 2) NOT NULL,
	StudentID INT FOREIGN KEY REFERENCES Students(StudentID)
);
