CREATE DATABASE LibraryDb
GO

USE LibraryDb
GO

CREATE TABLE Contacts (
	Id INT IDENTITY PRIMARY KEY
	, Email NVARCHAR(100)
	, PhoneNumber NVARCHAR(20)
	, PostAddress NVARCHAR(200)
	, Website NVARCHAR(50)
)

CREATE TABLE Authors (
	Id INT IDENTITY PRIMARY KEY
	, Name NVARCHAR(100) NOT NULL 
	, ContactId INT CONSTRAINT FK_Authors_Contacts FOREIGN KEY REFERENCES Contacts(Id) NOT NULL
)

CREATE TABLE Genres (
	Id INT IDENTITY PRIMARY KEY
	, Name NVARCHAR(30) NOT NULL
)

CREATE TABLE Books (
	Id INT IDENTITY PRIMARY KEY
	, Title NVARCHAR(100) NOT NULL
	, YearPublished INT NOT NULL
	, ISBN NVARCHAR(13) UNIQUE NOT NULL
	, AuthorId INT CONSTRAINT FK_Books_Authors FOREIGN KEY REFERENCES Authors(Id) NOT NULL
	, GenreId INT CONSTRAINT FK_Books_Genres FOREIGN KEY REFERENCES Genres(Id) NOT NULL
)

CREATE TABLE Libraries (
	Id INT IDENTITY PRIMARY KEY
	, Name NVARCHAR(50) NOT NULL
	, ContactId INT CONSTRAINT FK_Libraries_Contacts FOREIGN KEY REFERENCES Contacts(Id) NOT NULL
)

CREATE TABLE LibrariesBooks (
	LibraryId INT CONSTRAINT FK_LibrariesBooks_Libraries FOREIGN KEY REFERENCES Libraries(Id) NOT NULL
	, BookId INT CONSTRAINT FK_LibrariesBooks_Books FOREIGN KEY REFERENCES Books(Id) NOT NULL
	, CONSTRAINT PK_LibrariesBooks PRIMARY KEY (LibraryId, BookId) 
)
